# Generated by Django 2.1.7 on 2019-03-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrosesByString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_number', models.CharField(default='', max_length=30)),
                ('cros_number', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'api_crosesbystring',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(default='', max_length=100)),
                ('data', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'api_email',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('referred_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'api_mark',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('referred_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('terms', models.CharField(max_length=50)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='API.Mark')),
            ],
            options={
                'db_table': 'api_model',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(default='', max_length=30)),
                ('prise', models.CharField(default='', max_length=10)),
                ('retail', models.CharField(default='', max_length=10)),
                ('brend', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('referred_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_part',
            },
        ),
        migrations.CreateModel(
            name='PartDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30)),
                ('prise', models.CharField(default='', max_length=10)),
                ('retail', models.CharField(default='', max_length=10)),
                ('brend', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'api_partdescription',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_source',
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('referred_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_subgroup', models.CharField(default='', max_length=150)),
                ('code_subgroup', models.CharField(default='', max_length=100)),
                ('name_group', models.CharField(default='', max_length=150)),
                ('code_group', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'api_subgroup',
            },
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('referred_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('vol', models.CharField(default='', max_length=150)),
                ('terms', models.CharField(default='', max_length=50)),
                ('body_type', models.CharField(default='', max_length=150)),
                ('cyl', models.CharField(default='', max_length=5)),
                ('drive', models.CharField(default='', max_length=150)),
                ('eng', models.CharField(default='', max_length=150)),
                ('fuel', models.CharField(default='', max_length=50)),
                ('hp', models.CharField(default='', max_length=50)),
                ('kw', models.CharField(default='', max_length=50)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='API.Model')),
            ],
            options={
                'db_table': 'api_typecar',
            },
        ),
        migrations.AddField(
            model_name='subgroup',
            name='typecar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='API.TypeCar'),
        ),
        migrations.AddField(
            model_name='part',
            name='subgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='API.SubGroup'),
        ),
    ]
