# Generated by Django 2.0.3 on 2018-09-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='type_id',
        ),
    ]
