# Generated by Django 2.0.3 on 2018-09-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_part_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosesByString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_number', models.CharField(default='', max_length=30)),
                ('cros_number', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PartDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30)),
                ('prise', models.CharField(default='', max_length=10)),
                ('retail', models.CharField(default='', max_length=10)),
                ('brend', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='subgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='API.SubGroup'),
        ),
    ]
