# Generated by Django 2.0.3 on 2019-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20180928_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(default='', max_length=100)),
                ('data', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
