# Generated by Django 2.0.3 on 2019-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumbersWithOutDuplicates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
