# Generated by Django 2.0.3 on 2019-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_partnumberswithoutduplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(default='', max_length=30)),
                ('name_image', models.CharField(default='', max_length=50)),
                ('tab_image', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
