# Generated by Django 2.0.3 on 2019-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_imege'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdescription',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partdescription',
            name='khmelnitskiy',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='partdescription',
            name='kiyivone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='partdescription',
            name='kiyivtwo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='partdescription',
            name='vinnitsa',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='partdescription',
            name='zhitomir',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='partdescription',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
